service: first-node-js-app

provider:
  name: aws
  runtime: nodejs12.x
  profile: sandbox

functions:
  Hello:
    handler: handler.hello
    environment: 
      TEST_ENV: This is Test Environment Variable  
  ListBuckets:
    handler: handler.listBuckets
  SendEmail:
    handler: handler.sendEmail
  SendTemplatedEmail:
    handler: handler.sendTemplatedEmail
  SendBulkTemplatedEmail:
    handler: handler.sendBulkTemplatedEmail
  HttpGotClient:
    handler: handler.httpGotClient
