service: first-node-js-app

provider:
  name: aws
  runtime: nodejs12.x
  profile: sandbox

functions:
  Hello:
    handler: handler.hello
  ListBuckets:
    handler: handler.listBuckets
  SendEmail:
    handler: handler.sendEmail
  SendTemplatedEmail:
    handler: handler.sendTemplatedEmail
  HttpGotClient:
    handler: handler.httpGotClient
